### ISSUE TITLE
v0.15.0 Release checklist

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator-angular#1214]
In order to release a new version, the following things need to happen:

 - [ ] Test new gulp changes around useref
 - [ ] Make sure imagemin works (1.0.0)
 - [ ] Update Readme with peerDependencies install note
 - [ ] Update Yo.io codelab with peerDependencies install and other changes
