### ISSUE TITLE
Generator Roadmap

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator-angular#553]
In an effort to be more transparent about the project, we are creating roadmaps for everything. This is the tentative roadmap for the Angular generator.
## Priority 1
- [ ] Refactor all the tests to test everything, including all existing options
- [ ] Make everything configurable. This will include a combination of flags, prompts and a configuration file
  - File casing in both scripts and filenames
  - Paths to where things are located [tip](https://github.com/yeoman/generator-backbone/pull/181)
  - Preprocessors declaration
- [ ] Support the project as a sub-generator for other projects (Angular full stack, MEAN stack, etc). This should happen as a side-effect of making everything configurable.
- [ ] Different organization of files. This includes the by module (proposed AngularJS team recommendation), or by function (current). Also where assets go in dev mode (CSS, JS, HTML)
## Priority 2
- [x] Remove minsafe files. [Done](https://github.com/yeoman/generator-angular/commit/c24e25097acb109240f687ace7c214b095d3ee77)
- [x] Consolidate all template files/folders into a central location [Done](https://github.com/yeoman/generator-angular/commit/22f2f2c3abf3df58a37daec95e6c0e62b9120057)
- [x] Add gulp as a build tool
- [ ] Add support for JS templates (#277)
- [ ] Add Protractor E2E tests and templates
- [ ] Add option for UI-Router
## Priority 3
- [X] Add support for TypeScript (#313, #539)
- [ ] Add support for BabelJS
- [ ] Add support for Stylus, Less
- [ ] Add support for Jade (#420)
- [ ] Remove heavy reliance on Bootstrap so other frameworks can be used (maybe as a prompt choice)
- [ ] Make vanilla CSS (no framework selected) more visually appealing
- [ ] Add ESLint to the project (probably replaces JSHint)
## Priority 4
- [ ] Support for backend implementations, whether that be proxies, rewrite rules, make it more composable for other generators or actually adding a backend REST server (highly unlikely though)
- [ ] uncss? remove css styles

If you think there are other things that should be added to the roadmap, or have questions about any of these, please feel free to comment.

**Comment by OminStyle** [comment]
+1 for ui-route and Protractor

**Comment by avdd** [comment]
Can I suggest less stuff and more explanation & composability? 

In creating a new project, I'd much rather be adding the things I want than removing the things I don't.

Also, teach to fish, etc.

**Comment by ProLoser** [comment]
I disagree. Add all the things. 

I actually never use generators or boilerplates, always bloated and out of date lol.

**Comment by avdd** [comment]
@ProLoser I'm starting to agree with you I think.  Bloated, out of date, inscrutable, over-opinionated, brittle and often just broken.  They seem to be solving the wrong problem.  It seems the only real use case is writing your own generators, at which point you're probably better off just having plain old templates at the ready.

**Comment by tonygemcd** [comment]
Best wishes,
Tony

**Comment by nicolasgarnil** [comment]
Is ngtemplates integration already merged? Could someone provide an example of how to integrate it with an application generated by `generator-angular`?

**Comment by qudrat-berlin** [comment]
+1 for material support and module file structure

**Comment by jonathanobino** [comment]
+1 for integrating gulp instead of grunt

**Comment by pensierinmusica** [comment]
+1 for ui-router

**Comment by circy** [comment]
+1 angular-material

**Comment by enbashi** [comment]
+1 for material support

**Comment by deerawan** [comment]
+1 protractor

**Comment by madvas** [comment]
+1 material angular
+1 module file structure
+1 gulp
:)

**Comment by brunowego** [comment]
+1 for adding ui-router

**Comment by gintsgints** [comment]
protractor - already done
ui-router - already done

Please check real status before posting ideas here.

**Comment by dancancro** [comment]
Also, send a message to support@github.com requesting that the feature voting feature be added to github so that people don't have to use "+1" comments.

[Everyone wants this](https://github.com/isaacs/github/issues/9) and the only way it's going to happen is if GitHub support gets flooded with requests.

**Comment by kiranps** [comment]
+1 for ui-router.

**Comment by vamsivarikuti** [comment]
+1 - less
+1 - uncss
+1 - materializecss


Waiting for this project to update more than an year now :disappointed:

**Comment by aendrew** [comment]
Is any of this even relevant anymore? I've been using [Swiip/generator-gulp-angular](http://www.github.com/Swiip/gulp-angular) lately, and it's fantastic, and is basically everything this issue is wanting to go for. The only downside is I've had to use [doronsever/gulp-angular-subtask](https://github.com/doronsever/generator-gulp-angular-subtask) for the sub-generators, and it seems out of date and using a different directory structure than gulp-angular. 

Perhaps a better use of time would be to create configuration for `generator-angular` so its sub-generators could more seamlessly be used with projects gulp-angular and [DaftMonk/generator-angular-fullstack](https://github.com/DaftMonk/generator-angular-fullstack). Although I'd really like to see a first-party Yeoman Angular release using Gulp, and ui-router, and all the radness rolled into, well, gulp-angular, it would also be really good to realise that these other projects have grown in its absence, and figuring out how this ecosystem can work better together might ultimately be more effective.

**Comment by gintsgints** [comment]
I like fact that angular-fullstack generates also server side stuff.

**Comment by kiranps** [comment]
currently views are created as separate html files. is it a good idea to merge all views with the index file when we build it

**Comment by Frondor** [comment]
Implement the use of ui-router as an alternative to the native ngRoute!

**Comment by gintsgints** [comment]
You can create new app with ui-router.

**Comment by rgstephens** [comment]
+1 for adding ui-router

**Comment by naughtydavid** [comment]
+1 for ui-router
May be this can be a configurable as to which routing module to use.
Same for ui-bootstrap

**Comment by DanPantry** [comment]
> Support for backend implementations, whether that be proxies, rewrite rules, make it more composable for other generators or actually adding a backend REST server (highly unlikely though)

have you considered using [webpack](https://www.npmjs.com/package/webpack)?  Comes with a easy to set up backend server that supports proxying. Also would serve well as a build step and allows for using CommonJS require in the browser

**Comment by aendrew** [comment]
@DanPantry I've been investigating using Webpack with Angular the last two days, have been fairly impressed so far. [This generator](https://github.com/gunta/generator-angular-webpack) looks really cool, despite it being Grunt-based.

**Comment by AbraaoAlves** [comment]
Have you seen the [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) ? What do you think of it?

A long time it has support for several things that have not been started here. eg jade, angularMaterial , typescript , protractor ... 

So, what do you recommend?

**Comment by aendrew** [comment]
@AbraaoAlves I [mentioned that above](https://github.com/yeoman/generator-angular/issues/553#issuecomment-96188710), am really impressed by it so far.

**Comment by clinton2111** [comment]
@eddiemonge Add an option to chose Angular-Ui-Router instead of the default router.

**Comment by javarch** [comment]
Ich werde ab  19.10.2015 nicht im B�ro sein. Ich kehre zur�ck am
23.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Generator Roadmap (#553)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by type0lang** [comment]
+1 for Protractor E2E tests and templates
+1 for ui.router

**Comment by andreybleme** [comment]
:+1: angular-material and angular-ui-router instead of default router.

**Comment by anandchristal** [comment]
@eddiemonge  ratherthan livereaload ,why can't move to "browsersyc"....highly powerful one.

**Comment by anandchristal** [comment]
@eddiemonge rather than livereload ,why can't move to "browsersync"....highly powerful one.

**Comment by federico-coraglio** [comment]
Do you think to update all dependency to the last version on package.json? because the generator is using https://github.com/gruntjs/grunt-contrib-livereload and it is deprecated.
